version: '3.8'

services:
#  tomcat:
#    image: tomcat:9.0
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT
#      - ./src/main/resources/hibernate.cfg.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/hibernate.cfg.xml
#      - ./target/classes:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes
#    networks:
#      - default-network
#    environment:
#      - DB_URL=${DB_URL}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#    depends_on:
#      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - default-network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      # - ./db-data/:/var/lib/postgresql/data/
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default-network:
    driver: bridge
